# Site settings
title: christopher himes
author: Christopher Himes
email: Christopher@christopherhimes.com
description: > # this means to ignore newlines until "baseurl:"
  Christopher Himes lives in Metro Detroit.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://christopherhimes.com" # the base hostname & protocol for your site
github_username:  christopherhimes
permalink: /blog/:year/:month/:day/:title.html

social-network-links:
  email: "christopher@christopherhimes.com"
  github: christopherhimes
  mastodon: "hachyderm.io/@eeentropyyy"
  rss: true  

comments:
  host: hachyderm.io
  username: eeentropyyy

navbar-links:
  About Me: "about"

###########################
# --- General options --- #
###########################

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/img/new-face.webp"
generic_share: "/assets/og-images/hi-there.webp"

# By default, the image is cut into a circle. You can disable this behavior by setting 'round-avatar: false'
round-avatar: false

# Excerpt word length - Truncate the excerpt of each post on the feed page to the specified number of words
excerpt_length: 250
excerpt_separator: <!--more-->

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Build settings
rss-description: "Christopher Himes RSS Feed"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude: 
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.webp
  - docs/
exclude: [vendor]
  
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll_reading_time
  # - jekyll-webmention_io


pagination:
  enabled: true
  per_page: 5
  permalink: '/blog/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# jekyll-minifier:
#   exclude: 'rss.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
#   preserve_php: false                # Default: false
#   remove_spaces_inside_tags: true   # Default: true
#   remove_multi_spaces: true         # Default: true
#   remove_comments: true             # Default: true
#   remove_intertag_spaces: false      # Default: false
#   remove_quotes: false              # Default: false
#   compress_css: true                # Default: true
#   compress_javascript: true         # Default: true
#   compress_json: true               # Default: true
#   simple_doctype: false             # Default: false
#   remove_script_attributes: false   # Default: false
#   remove_style_attributes: false    # Default: false
#   remove_link_attributes: false     # Default: false
#   remove_form_attributes: false     # Default: false
#   remove_input_attributes: false    # Default: false
#   remove_javascript_protocol: false # Default: false
#   remove_http_protocol: false       # Default: false
#   remove_https_protocol: false      # Default: false
#   preserve_line_breaks: false       # Default: false
#   simple_boolean_attributes: false  # Default: false
#   compress_js_templates: false      # Default: false
#   preserve_patterns:                # Default: (empty)
#   uglifier_args:                    # Default: (empty)

# webmentions:
#   username: christopherhimes.com
#   pages: true
#   collections:
#     - webmentions