# Site settings
title: Christopher Himes
email: Christopher@christopherhimes.com
description: > # this means to ignore newlines until "baseurl:"
  Christopher Himes is a Software Developer living in Metro Detroit.
  This is an account of his personal projects and inquiries in the world of
  development.  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://christopherhimes.com" # the base hostname & protocol for your site
twitter_username: eeentropyyy
github_username:  christopherhimes
permalink: /blog/:categories/:year/:month/:day/:title.html

# Build settings
markdown: kramdown
